name: Build Windows Installer

on: [push]

jobs:
  buildOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Package
        run: ./gradlew jpackage
      - uses: actions/upload-artifact@v2
        with:
          name: Win-installer
          path: build/distributions/*
